### ISSUE TITLE
Russian translation 

### ISSUE THREAD

**Issue by hzlmn** [h5bp/movethewebforward#101]
hi, i very love this resource and want to make translation of it on my native language. Does it make sense for you and how i can contribute?

**Comment by arthurvr** [comment]
Every contribution is welcome, but honestly, I wonder if we want (more) translations. Translations always turn out be hard to maintain, for html5boilerplate.com we totally removed them for that reason. I'd like to hear some other thoughts on this tho. /cc @h5bp/movethewebforward 

> and how i can contribute?

There are many ways you can contribute, and any contribution is welcome! Take a look at the open issues. Also, it seems like many links on the site get outdated quickly so any updates/additions to them are welcome.

**Comment by arthurvr** [comment]
@h5bp/movethewebforward What do we think about this one? I'd rather see us removing the translations than adding new ones.

**Comment by drKraken** [comment]
@arthurvr in my opinion,translations are very useful for moving web forward, because it can fix some language barriers , but project needs in supporters for each type of translation, who will keep an eye on the relevance of translation.
