### ISSUE TITLE
Link to Test the Web Forward

### ISSUE THREAD

**Issue by xfq** [h5bp/movethewebforward#111]
What about adding a link to [Test the Web Forward](http://testthewebforward.org/)? Maybe under the "Contribute to Test Suites" section.

**Comment by arthurvr** [comment]
What's the current status of that project? Is it still really alive? The latest blogpost was a year ago...

**Comment by joel-powers** [comment]
It looks active to me... Lots of activity in the repo lately.

**Comment by cvrebert** [comment]
[The underlying project](https://github.com/w3c/web-platform-tests) which it serves as the contributor documentation of is very much alive.
