### ISSUE TITLE
MS Edge developer blog/etc.

### ISSUE THREAD

**Issue by joel-powers** [h5bp/movethewebforward#113]
MS have shifted all of their developer discussion away from IE, to the new Edge resources. This has resulted in a few broken links on index.html (and possible other places?)

**Comment by joel-powers** [comment]
I have replaced these links in [my fork](https://github.com/joel-powers/movethewebforward/commit/ab467e240d34e2b8e2e9e85ab8cb11c0cf74abec). I'm open to fixing this in whatever way is most acceptable to you (plural).

**Comment by arthurvr** [comment]
Thanks!

**Comment by arthurvr** [comment]
Leaving the issue open if anyone is interested in fixing the translations.

**Comment by joel-powers** [comment]
Does it make sense to directly reach out to those people who contributed translation in the past? I'm not sure how that would fit etiquette here, but it might get this closed a little faster. Just an idea.

**Comment by arthurvr** [comment]
We never really had an active maintainer for those translations and I'd honestly rather see them going away then going through the pain of maintaining them.
