### ISSUE TITLE
Twitter avatars broken

### ISSUE THREAD

**Issue by joel-powers** [h5bp/movethewebforward#115]
Obviously, the Twitter avatars aren't showing up in any on the sections. I'm about to start working on that part (starting in init.js) that makes the API call for the avatars. If anyone is interested in making this work and you have more time than I do, feel free to jump in. Comments here, please. :-)

**Comment by joel-powers** [comment]
To add to what I wrote above, I'd like to get this to call for the `user_id` instead of the `user_name`. I've found that a lot of the pledges are using the same handle, but the API broke the avatar loading. But changoing how we get the data may allow our code to continue working should they change their handle.

**Comment by joel-powers** [comment]
I don't know why I didn't see the previously opened issue before now. Consider this closed. I will work on the older ticket. Oops!

**Comment by arthurvr** [comment]
No worries :)
