### ISSUE TITLE
Is this site abandoned?

### ISSUE THREAD

**Issue by dmitriz** [h5bp/movethewebforward#121]
No updates since Aug 2015?

**Comment by dmitriz** [comment]
This is how it right columns look in my Chrome v. 49:

http://cl.ly/1s3K0v3l0I2z

**Comment by paulirish** [comment]
mostly abandoned yes.

but i fixed that bug for you. :)

**Comment by dmitriz** [comment]
Sorry to hear it is abandoned, was looking promising ;(

And thanks for the bug fixing, appreciated!
