### ISSUE TITLE
Staler Than Week Old Bread... Archive this Project?

### ISSUE THREAD

**Issue by roblarsen** [h5bp/movethewebforward#126]
This project has gone stale. The intent and idea are both still valid, unfortunately, the content is not (there's a YUI mention in there somewhere.) 

Unless someone has an interest in taking this on, I'm going to archive the project. I'll leave this open for a while to catch comments and volunteers. I'm going to be working on nurturing the active H5BP projects and, as part of that, I want to clearly identify what we're still working on/is still valid (in the case of projects which are merely relatively stable but still useful.)

**Comment by paulirish** [comment]
sg. i have been keeping the domain alive but yah the content is pretty aged. :/

**Comment by roblarsen** [comment]
Thanks, Paul. 

I'm going to go ahead with the plan to archive this project.
